CREATE TABLE vehicles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    make               VARCHAR(100)             NOT NULL,
    model              VARCHAR(100)             NOT NULL,
    production_year    INTEGER                  NOT NULL,
    vin                VARCHAR(17) UNIQUE,
    license_plate      VARCHAR(20),
    fuel_type          VARCHAR(20)              NOT NULL,
    current_mileage_km INTEGER                  NOT NULL DEFAULT 0,
    purchase_date      DATE,
    purchase_price     NUMERIC(12, 2),
    active             BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_vehicles_production_year
        CHECK (production_year >= 1886),
    CONSTRAINT chk_vehicles_current_mileage
        CHECK (current_mileage_km >= 0),
    CONSTRAINT chk_vehicles_purchase_price
        CHECK (purchase_price IS NULL OR purchase_price >= 0),
    CONSTRAINT chk_vehicles_vin
        CHECK (
            vin IS NULL
                OR vin ~ '^[A-HJ-NPR-Z0-9]{17}$'
            ),
    CONSTRAINT chk_vehicles_fuel_type
        CHECK (
            fuel_type IN (
                          'PETROL',
                          'DIESEL',
                          'HYBRID',
                          'ELECTRIC',
                          'LPG',
                          'OTHER'
                )
            )
);
CREATE TABLE fuel_entries
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vehicle_id      BIGINT                   NOT NULL,

    filled_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    odometer_km     INTEGER                  NOT NULL,
    liters          NUMERIC(8, 3)            NOT NULL,
    price_per_liter NUMERIC(8, 3)            NOT NULL,
    total_cost      NUMERIC(12, 2)           NOT NULL,
    full_tank       BOOLEAN                  NOT NULL DEFAULT FALSE,
    fuel_station    VARCHAR(100),
    notes           TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fuel_entries_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE,
    CONSTRAINT chk_fuel_entries_odometer
        CHECK (odometer_km >= 0),
    CONSTRAINT chk_fuel_entries_liters
        CHECK (liters > 0),
    CONSTRAINT chk_fuel_entries_price_per_liter
        CHECK (price_per_liter >= 0),
    CONSTRAINT chk_fuel_entries_total_cost
        CHECK (total_cost >= 0)
);
CREATE TABLE service_records
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vehicle_id   BIGINT                   NOT NULL,

    service_type VARCHAR(50)              NOT NULL,
    service_date DATE                     NOT NULL,
    odometer_km  INTEGER                  NOT NULL,

    description  TEXT                     NOT NULL,
    workshop     VARCHAR(150),

    cost         NUMERIC(12, 2)           NOT NULL,
    notes        TEXT,

    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_records_vehicle
        FOREIGN KEY (vehicle_id)
            REFERENCES vehicles (id)
            ON DELETE CASCADE,
    CONSTRAINT chk_service_records_odometer
        CHECK (odometer_km >= 0),
    CONSTRAINT chk_service_records_cost
        CHECK (cost >= 0)
);
CREATE TABLE expenses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vehicle_id   BIGINT                   NOT NULL,

    expense_type VARCHAR(50)              NOT NULL,
    expense_date DATE                     NOT NULL,
    amount       NUMERIC(12, 2)           NOT NULL,

    description  TEXT,

    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_expenses_vehicle
        FOREIGN KEY (vehicle_id)
            REFERENCES vehicles (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_expenses_amount
        CHECK (amount > 0)
);


CREATE TABLE maintenance_tasks
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vehicle_id     BIGINT                   NOT NULL,

    title          VARCHAR(150)             NOT NULL,
    description    TEXT,

    due_date       DATE,
    due_mileage_km INTEGER,

    status         VARCHAR(30)              NOT NULL DEFAULT 'PENDING',
    completed_at   TIMESTAMP WITH TIME ZONE,

    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_maintenance_tasks_vehicle
        FOREIGN KEY (vehicle_id)
            REFERENCES vehicles (id)
            ON DELETE CASCADE,
    CONSTRAINT chk_maintenance_tasks_due_mileage
        CHECK (
            due_mileage_km IS NULL
                OR due_mileage_km >= 0
            ),
    CONSTRAINT chk_maintenance_tasks_due_condition
        CHECK (
            due_date IS NOT NULL
                OR due_mileage_km IS NOT NULL
            )
);
CREATE INDEX idx_fuel_entries_vehicle_filled_at
    ON fuel_entries (vehicle_id, filled_at DESC);

CREATE INDEX idx_service_records_vehicle_service_date
    ON service_records (vehicle_id, service_date DESC);

CREATE INDEX idx_expenses_vehicle_expense_date
    ON expenses (vehicle_id, expense_date DESC);

CREATE INDEX idx_maintenance_tasks_vehicle_status
    ON maintenance_tasks (vehicle_id, status);
